### ISSUE TITLE
decktape: permission denied

### ISSUE THREAD

**Issue by drasch** [arnehilmann/markdeck#17]
Generating of PDF from UID=1001 on host, gets Permission denied on PDF generation. 

```
pdf_1         | touch: /slides/.meta/pdf_rendered: Permission denied
pdf_1         | starting pdf rendering
pdf_1         | TypeError: Unable to create PDF file, make sure that output file target is available
pdf_1         |     at /decktape/decktape.js:196:26
pdf_1         |     at <anonymous>
pdf_1         |     at process._tickCallback (internal/process/next_tick.js:182:7)
pdf_1         | pdf rendering finished
web_1         | Change detected index.html
pdf_1         | touch: /slides/.meta/pdf_rendered: Permission denied
pdf_1         | starting pdf rendering
pdf_1         | TypeError: Unable to create PDF file, make sure that output file target is available
pdf_1         |     at /decktape/decktape.js:196:26
pdf_1         |     at <anonymous>
pdf_1         |     at process._tickCallback (internal/process/next_tick.js:182:7)
pdf_1         | pdf rendering finished
pdf_1         | touch: /slides/.meta/pdf_rendered: Permission denied
pdf_1         | starting pdf rendering
pdf_1         | TypeError: Unable to create PDF file, make sure that output file target is available
pdf_1         |     at /decktape/decktape.js:196:26
pdf_1         |     at <anonymous>
pdf_1         |     at process._tickCallback (internal/process/next_tick.js:182:7)
pdf_1         | pdf rendering finished
```

**Comment by drasch** [comment]
Doesn't look like `decktape` honors the MARKDECK_USER env variable.

**Comment by arnehilmann** [comment]
ouch, that might be the case...
(and I have to check my notification settings for this project)
